sprintf(buffer,"**System used for compilation:\n");
output_string(buffer);
sprintf(buffer,"**Linux tmac-sgx 3.19.8-ckt12 #17 SMP Mon Jan 9 14:46:20 CST 2017 x86_64 x86_64 \n");
output_string(buffer);
sprintf(buffer,"**C compiler: /home/tmac/workspace/sgx-driver/musl-libc/build/bin/musl-gcc\n");
output_string(buffer);
sprintf(buffer,"**libc: \n");
output_string(buffer);
sprintf(buffer,"**Date of compilation: 2017年 02月 19日 星期日 22:35:56 CST\n");
output_string(buffer);
